// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactGrid = require("bs-react-grid/src/ReactGrid.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("MyFirstGrid");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var layout = /* array */[
                ReactGrid.layout(1, 1, 0, 0, "a", undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, /* () */0),
                ReactGrid.layout(3, 2, 1, 0, "b", 2, 4, undefined, undefined, undefined, undefined, undefined, undefined, ".react-grid-handle", /* () */0),
                ReactGrid.layout(1, 2, 4, 0, "c", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0)
              ];
              return ReasonReact.element(undefined, undefined, ReactGrid.ReactGridLayout[/* make */2]("layout", undefined, 100, undefined, 12, undefined, undefined, undefined, undefined, layout, undefined, undefined, 30, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[
                              ReasonReact.element(undefined, undefined, ReactGrid.GridItem[/* make */0](undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[React.createElement("div", {
                                              key: "a"
                                            }, "a")])),
                              React.createElement("div", {
                                    key: "b"
                                  }, React.createElement("div", {
                                        className: "react-grid-handle"
                                      }, "handle"), React.createElement("br", undefined), React.createElement("br", undefined), "b"),
                              React.createElement("div", {
                                    key: "c"
                                  }, "c")
                            ]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
