// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactGrid = require("bs-react-grid/src/ReactGrid.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("MyFirstGrid");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var layout = /* array */[
                ReactGrid.layout(1, 1, 0, 0, "a", /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[true], /* None */0, /* None */0, /* () */0),
                ReactGrid.layout(3, 2, 1, 0, "b", /* Some */[2], /* Some */[4], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* () */0),
                ReactGrid.layout(1, 2, 4, 0, "c", /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* () */0)
              ];
              return ReasonReact.element(/* None */0, /* None */0, ReactGrid.ReactGridLayout[/* make */2](/* Some */["layout"], /* None */0, /* Some */[100], /* None */0, /* Some */[12], /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[layout], /* None */0, /* None */0, /* Some */[30], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[
                              ReasonReact.element(/* None */0, /* None */0, ReactGrid.GridItem[/* make */0](/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[React.createElement("div", {
                                              key: "a"
                                            }, "a")])),
                              React.createElement("div", {
                                    key: "b"
                                  }, "b"),
                              React.createElement("div", {
                                    key: "c"
                                  }, "c")
                            ]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
